server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@metaverse.ohgiraffers.com:1521/xe
    username: C##FAIRYTALER
    password: FAIRYTALER
  data:
    mongodb:
      uri : mongodb+srv://fairytaler:fairytaler@fairytaler.10ybul3.mongodb.net/?retryWrites=true&w=majority
      authentication-database: admin
      database: my-database
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
jwt:
  secret: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.fairytaler.fairytalecat
  configuration:
    map-underscore-to-camel-case: true