name: fairytaler-backend Server CI/CD

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  # Java
  JAVA_VERSION: 11
  # DockerHub
  DOCKER_HUB_USERNAME: jihi1013
  # AWS & Elastic Bean Stalk
  AWS_REGION: ap-northeast-2
  EB_ENVIRONMENT_NAME: Fairytalerback-env
  EB_APPLICATION_NAME: Fairytaler-back
  spring.datasource.url: ${{ secrets.DATASOURCE_URL }} 
  spring.datasource.username: ${{ secrets.DATASOURCE_USERNAME }} 
  spring.datasource.password: ${{ secrets.DATASOURCE_PASSWORD }} 
  jwt.secret: ${{ secrets.JWT_SECRET }}   
  APPLICATION: ${{ secrets.APPLICATION }}

jobs:
  build:
    name: CI PipeLine
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Set application.yml from Secrets
      uses: actions/checkout@v2
    - run: touch ./src/main/resources/application.yml
    - run: echo "${{env.APPLICATION}}" > ./src/main/resources/application.yml
    - uses: actions/upload-artifact@v2
      with:
        name: application.yml
        path: ./src/main/resources/application.yml
    
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Login to DockerHub
      run: docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      
    - name: Build DockerImage
      run: docker build -t ${{ env.DOCKER_HUB_USERNAME }}/backend:latest ./
        
    - name: Push DockerImage
      run: docker push ${{ env.DOCKER_HUB_USERNAME }}/backend:latest

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
  
  deploy:
      name: CD PipeLine
      runs-on: ubuntu-latest
      needs: build
      
      steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"    
          
      - name: Generate deployment directory
        run: |
          mkdir -p deploy
          cp Dockerrun.aws.json deploy/Dockerrun.aws.json
          cd deploy && zip -r deploy.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          version_label: fairytaler-cicd-${{steps.current-time.outputs.formattedTime}}
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 200
